#Fault clearing time in cycles, it required
#to specify one value for each grid model"""
fault_clearing_time__cycles:
  - 10
  - 12
#this parameters needs to be specified
#if load change is considered, one number in
#percentage for each grid model
max_load_change:
  - 60
  - 60
#The simulation time of the model
#during which the faults are studied
simulation_time: 10
#The number of contingencies or
#events needed to be simulated"""
number_of_events: 1
#1 for simulation of the events,
#0 for importing the pickle files
key_data: 0
#NewEngland or NineBusSystem
grid: NewEngland
#svm, clf, mlp, or rnn, dnn, ensb
ml_algorithm:
  #- svm
  #- clf
  #- mlp
  #- rnn
  #- dnn
  - ensb

#this parameters are required only in case
#of choosing any deep learning method
epochs: 10
batch_size: 32
optimizer: Adam
learning_rate: 0.01
n_steps: 1
#Parameter to adjust reduced features
reduced: 0
#0 for normal features, 1 for reduced


